openapi: 3.0.3
info:
  title: Log4Fit API
  description: API for the Log4Fit exercise tracking application.
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: Local Development
  - url: http://localhost:8083
    description: Production
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/v1/public-api:
    get:
      summary: Public Endpoint (v1)
      description: Returns a welcome message (Plain Text).
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /api/v2/public-api:
    get:
      summary: Public Endpoint (v2)
      description: Returns a welcome message (JSON).
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  requests_left:
                    type: string
  /api/v1/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User created
  /api/v1/auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
  /api/v1/auth/google:
    post:
      summary: Login with Google
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idToken:
                  type: string
      responses:
        '200':
          description: Login successful
  /api/v1/auth/refresh:
    post:
      summary: Refresh Token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token refreshed
  /api/v1/auth/me:
    get:
      summary: Get Current User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User details
  /api/v1/exercises:
    get:
      summary: Get All Exercises
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
        - name: q
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of exercises
  /api/v1/exercises/{id}:
    get:
      summary: Get Exercise by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Exercise details
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: OK
